---
- name: Install pm2 global package
  npm:
    name: azurite
    global: true
  register: pm2_installed

- name: Prepare directory for azurite data
  file:
    path: /var/lib/azurite
    owner: www-data
    group: www-data
    mode: 0755
    state: directory

- name: Prepare .npm directory
  become: true
  become_user: root
  file:
    path: /var/www/.pm2
    state: directory
    owner: www-data
    group: www-data

- name: Start application with pm2
  become: true
  become_user: www-data
  command: pm2 start azurite --name=azurite  -- -l /var/lib/azurite
  when: pm2_installed.changed
  tags:
    - skip_ansible_lint

- name: Save the pm2 process list
  become: true
  become_user: www-data
  command: "pm2 save"
  when: pm2_installed.changed
  tags:
    - skip_ansible_lint
